sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t vvsaggie/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true vvsaggie/docker-react npm run test
